[package]
name = "evse-rs"
version = "0.1.0"
edition = "2024"


[dependencies]
ocpp-rs = {git = "https://github.com/unwize/ocpp-rs.git"}
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
tokio-tungstenite = "0.28.0"
futures-util = "0.3.31"
rootcause = "0.11.0"