[package]
name = "evse-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
miette = { version = "7.6.0", features = ["fancy"] }
ocpp-rs = {git = "https://github.com/unwize/ocpp-rs.git"}
thiserror = "2.0.17"
